name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables
        run: cp ~/.env ~/actions-runner/_work/hpbot/hpbot/.env

      - name: Restart App
        run: pm2 restart HPBot
